sonar.projectKey=Lumina
sonar.projectName=Lumina Fullstack
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

# 1. FUENTES (Donde está todo el código, incluyendo los tests del front)
sonar.sources=api/app,app/src

# 2. TESTS (Aquí viene el truco)
# Solo dejamos 'api/tests' porque esa carpeta SÍ está separada del código fuente del backend.
# Quitamos 'app/src/tests' de aquí para evitar el conflicto.
sonar.tests=api/tests

# 3. IDENTIFICAR TESTS DEL FRONTEND (El Magia)
# Le decimos: "Cualquier archivo dentro de las fuentes que termine así, es un test"
sonar.test.inclusions=**/*.test.jsx,**/*.test.js

# 4. REPORTES
sonar.python.coverage.reportPaths=api/coverage.xml
sonar.javascript.lcov.reportPaths=app/coverage/lcov.info

# 5. EXCLUSIONES GENERALES (Archivos basura)
sonar.exclusions=**/node_modules/**,**/venv/**,**/__pycache__/**,**/*.db,**/dist/**,**/build/**

# 6. EXCLUSIONES DE COBERTURA (Para que no te baje el promedio)
# Aunque Sonar ya sabe que son tests, esto asegura que no pida coverage para archivos de configuración
sonar.coverage.exclusions=**/migrations/**,**/*.config.js,**/main.jsx,**/index.js