"""Creacion inicial de tablas Ramo, Hito, Tarea

Revision ID: 0009e38baab1
Revises: 
Create Date: 2025-11-17 01:15:10.799322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0009e38baab1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ramo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('prioridad', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('porcentaje_evaluacion', sa.Float(), nullable=True),
    sa.Column('importancia', sa.Integer(), nullable=True),
    sa.Column('ramo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ramo_id'], ['ramo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('completada', sa.Boolean(), nullable=True),
    sa.Column('tiempo_dedicado', sa.Integer(), nullable=True),
    sa.Column('hito_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hito_id'], ['hito.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarea')
    op.drop_table('hito')
    op.drop_table('ramo')
    # ### end Alembic commands ###
