"""Inicializacion desde cero

Revision ID: 3baadc027802
Revises: 
Create Date: 2025-11-19 14:37:51.619549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3baadc027802'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario')),
    sa.UniqueConstraint('email', name=op.f('uq_usuario_email'))
    )
    op.create_table('ramo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('prioridad', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_ramo_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ramo'))
    )
    op.create_table('hito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('porcentaje_evaluacion', sa.Float(), nullable=True),
    sa.Column('importancia', sa.Integer(), nullable=True),
    sa.Column('ramo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ramo_id'], ['ramo.id'], name=op.f('fk_hito_ramo_id_ramo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hito'))
    )
    op.create_table('tarea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('completada', sa.Boolean(), nullable=True),
    sa.Column('tiempo_dedicado', sa.Integer(), nullable=True),
    sa.Column('hito_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hito_id'], ['hito.id'], name=op.f('fk_tarea_hito_id_hito')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tarea'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarea')
    op.drop_table('hito')
    op.drop_table('ramo')
    op.drop_table('usuario')
    # ### end Alembic commands ###
