"""Añadir tabla Usuario y relacion con Ramo

Revision ID: c56a2995ff98
Revises: 0009e38baab1
Create Date: 2025-11-18 00:20:37.855502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c56a2995ff98'
down_revision = '0009e38baab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ramo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_ramo_usuario_id_usuario'), 'usuario', ['usuario_id'], ['id'])

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_usuario_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_usuario_email'), type_='unique')

    with op.batch_alter_table('ramo', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ramo_usuario_id_usuario'), type_='foreignkey')
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
