[pytest]
# Esta línea es la clave: añade la carpeta actual al path de Python
pythonpath = .

testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Aquí ya tienes configurado el coverage, así que bastará con correr "pytest"
addopts = --cov=app --cov-report=xml --cov-report=term-missing