sonar.projectKey=Lumina
sonar.projectName=Lumina Backend
sonar.projectVersion=1.0

# Especifica las rutas exactas
sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.8

# Excluir archivos que no son código
sonar.exclusions=**/migrations/**,**/venv/**,**/__pycache__/**,**/*.db
sonar.test.exclusions=**/venv/**,**/__pycache__/**

# Especificar encoding
sonar.sourceEncoding=UTF-8